version: "3.9"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "54320:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - "63790:6379"
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - ./.docker/redis:/data